### ISSUE TITLE
Error: random.bool is not a function

### ISSUE THREAD

**Issue by xinbenlv** [DiceBear/avatars#49]
```
/usr/local/google/home/zzn/ws/wikiloop-battlefield/node_modules/@dicebear/avatars-human-sprites/lib/index.js:9
    if (random.bool(50)) {
               ^

TypeError: random.bool is not a function
    at default_1 (/usr/local/google/home/zzn/ws/wikiloop-battlefield/node_modules/@dicebear/avatars-human-sprites/lib/index.js:9:16)
    at Object.<anonymous> (/usr/local/google/home/zzn/ws/wikiloop-battlefield/server/routes/avatar.js:17:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/google/home/zzn/ws/wikiloop-battlefield/server/routes/index.js:24:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/google/home/zzn/ws/wikiloop-battlefield/server/index.js:24:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
    at internal/main/run_main_module.js:16:11

```
## Debug: version
```json
{
  'wikiloop-battlefield': '3.0.1-beta',
  npm: '6.12.1',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '79',
  napi: '5',
  nghttp2: '1.39.2',
  node: '13.1.0',
  openssl: '1.1.1d',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.8.279.17-node.19',
  zlib: '1.2.11'
}
```
```json
   "@dicebear/avatars": {
      "version": "4.0.2",
      "resolved": "https://registry.npmjs.org/@dicebear/avatars/-/avatars-4.0.2.tgz",
      "integrity": "sha512-jVjUsZvKO5RypFE89+sFNMsu6vDQIPTNiputG1J8+EjQC0BLixfFCiI17UYLXA7xaBM2Md++y0BpnigxalbpTA==",
      "requires": {
        "pure-color": "^1.3.0",
        "seedrandom": "^2.4.3",
        "svgson": "^4.0.0"
      }
    },
    "@dicebear/avatars-female-sprites": {
      "version": "4.0.2",
      "resolved": "https://registry.npmjs.org/@dicebear/avatars-female-sprites/-/avatars-female-sprites-4.0.2.tgz",
      "integrity": "sha512-2jWHxCj+fVnx7wWmpksKABKicyOvfcEGMExv5i9vzob7vn/EdG9xUDYrtaYQPMDxCx/5D3x+SpfokfmE90FlPw=="
    },
    "@dicebear/avatars-human-sprites": {
      "version": "4.0.2",
      "resolved": "https://registry.npmjs.org/@dicebear/avatars-human-sprites/-/avatars-human-sprites-4.0.2.tgz",
      "integrity": "sha512-COp63a+E3D/LlJH9U5HIsfVID7QFpAo9ArWsoEWqckot38NZK53Q6cNwBhGXjIKVrVIgfXz7TZJiGKD3EUNxAQ==",
      "requires": {
        "@dicebear/avatars-female-sprites": "^4.0.2",
        "@dicebear/avatars-male-sprites": "^4.0.2"
      },
      "dependencies": {
        "@dicebear/avatars-male-sprites": {
          "version": "4.0.2",
          "resolved": "https://registry.npmjs.org/@dicebear/avatars-male-sprites/-/avatars-male-sprites-4.0.2.tgz",
          "integrity": "sha512-303iAO4pF5qheyopny0jxpo75jyPTNJ/86CwTc/zm9xy/LobirCnX4gXkP0/o7bId2XslBq1oCvcX3aTWshB1g=="
        }
      }
    },
    "@dicebear/avatars-identicon-sprites": {
      "version": "4.0.2",
      "resolved": "https://registry.npmjs.org/@dicebear/avatars-identicon-sprites/-/avatars-identicon-sprites-4.0.2.tgz",
      "integrity": "sha512-cILbAilZ2QLSSZQ5DZqeD4N20fO53llf9w7jDj4UZoP31jBbWjAKyuoRQxNOHUWAijh0nRFq0GSBjUN7yuxvPg=="
    },
    "@dicebear/avatars-male-sprites": {
      "version": "2.1.4",
      "resolved": "https://registry.npmjs.org/@dicebear/avatars-male-sprites/-/avatars-male-sprites-2.1.4.tgz",
      "integrity": "sha512-bQKzn95FG64YD8QcjBeVIjJvsKt67mRopISm6mDWkZGsUIwrJ5Kb4rJfdXikjYDYzAb0Vj9/US5uKqOTJf5uMA=="
    },
```

**Comment by FlorianKoerner** [comment]
Please use the version >= 4.0.0 for all Sprite Collections. And please note the changed api.

See also #47
